---
title: "Second Phase Data Filtering"
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---



```{r echo = FALSE, warning = FALSE, message = FALSE} 
#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggpubr) 
library(gsubfn)


#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
root_dir <- 'T:/Google Drive/University of Houston/CS - UH/@Research - CPL/@Projects/NsfStressDataCuration'
setwd(root_dir)

data_paper_dir <- file.path(root_dir, 'nsf-data-paper-scripts')
data_dir <- file.path(data_paper_dir, 'data')
plots_dir <- file.path(data_paper_dir, 'plots')

session_list <- c('RestingBaseline', 'StressCondition', 'BaselineWriting', 'DualTask', 'Presentation')

first_phase_filtered_data_file_name <- 'full_df_first_phase_filtered.csv'
bad_moderate_signal_file_name <- 'bad_moderate_signal.csv'
# mean_data_file_name <- 'result_df.csv'

# common_col_names <- c('Subject', 'Condition', 'Session', 'CovertedTime', 'TimeElapsed')
# hr_col_list <- c(common_col_names, hr_col_names)

first_phase_filtered_df <- tibble()
second_phase_filtered_df <- tibble()
bad_moderate_signal_df <- tibble()




#-------------------------#
#---FUNCTION DEFINITION---#
#-------------------------#
convert_to_csv <- function(df, file_name) {
  write.table(df, file = file.path(file_name), row.names=F, sep = ',')
}

print_msg <- function(msg) {
  print(msg)
  message(msg)
}

is_match <- function(str, pattern) { 
  return(grepl(pattern, str)) 
}

add_bad_moderate_signal <- function(subj, session, signal, condition) {
  bad_moderate_signal_df <<- rbind(bad_moderate_signal_df, 
                                  tibble(
                                    'Subject'=subj,
                                    'Session'=session,
                                    'Signal'=signal,
                                    'Condition'=condition
                                    )
                                  )
}

make_bad_moderate_signal_data <- function() {
  
  add_bad_moderate_signal('T011', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T016', 'SC', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T016', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T019', 'RB', 'N.HR', 'Bad')
  add_bad_moderate_signal('T019', 'SC', 'N.HR', 'Bad')
  add_bad_moderate_signal('T019', 'ST', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T019', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T031', 'RB', 'N.HR', 'Bad')
  add_bad_moderate_signal('T031', 'SC', 'N.HR', 'Bad')
  add_bad_moderate_signal('T031', 'DT', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T032', 'RB', 'N.HR', 'Bad')
  add_bad_moderate_signal('T032', 'SC', 'N.HR', 'Bad')
  add_bad_moderate_signal('T032', 'ST', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T032', 'DT', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T035', 'RB', 'N.HR', 'Bad')
  add_bad_moderate_signal('T035', 'SC', 'N.HR', 'Bad')
  add_bad_moderate_signal('T035', 'DT', 'N.HR', 'Bad')
  add_bad_moderate_signal('T035', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T047', 'RB', 'N.HR', 'Moderate') #####################
  add_bad_moderate_signal('T047', 'SC', 'N.HR', 'Bad') #####################
  
  add_bad_moderate_signal('T051', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T061', 'ST', 'N.HR', 'Bad')
  add_bad_moderate_signal('T061', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T063', 'P', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T064', 'ST', 'N.HR', 'Bad')
  add_bad_moderate_signal('T065', 'P', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T066', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T068', 'ST', 'N.HR', 'Bad')
  add_bad_moderate_signal('T068', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T078', 'ST', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T079', 'ST', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T082', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T083', 'SC', 'N.HR', 'Bad')
  add_bad_moderate_signal('T083', 'ST', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T085', 'P', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T091', 'ST', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T092', 'RB', 'HR', 'Moderate - Removed Bad Signal Part')
  add_bad_moderate_signal('T092', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T093', 'SC', 'N.HR', 'Bad')
  add_bad_moderate_signal('T094', 'P', 'N.HR', 'Bad')
  add_bad_moderate_signal('T099', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T106', 'ST', 'N.HR', 'Bad')
  add_bad_moderate_signal('T106', 'DT', 'N.HR', 'Bad') #####################
  add_bad_moderate_signal('T106', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T113', 'ST', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T113', 'P', 'N.HR', 'Moderate')
  
  add_bad_moderate_signal('T114', 'P', 'N.HR', 'Bad')
  add_bad_moderate_signal('T132', 'P', 'N.HR', 'Moderate') ## Need to check EDA
  add_bad_moderate_signal('T157', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T174', 'SC', 'N.HR', 'Moderate')
  add_bad_moderate_signal('T174', 'ST', 'N.HR', 'Bad')
  add_bad_moderate_signal('T174', 'P', 'N.HR', 'Bad')
  
  add_bad_moderate_signal('T176', 'ST', 'N.HR', 'Moderate')
  

  convert_to_csv(bad_moderate_signal_df, file.path(data_dir, 'bad_moderate_signal.csv'))
  # convert_to_csv(bad_moderate_signal_df, 'bad_moderate_signal.csv')
}








read_data <- function() {
  # first_phase_filtered_df <<- read_csv(file.path(data_dir, first_phase_filtered_data_file_name))
  second_phase_filtered_df <<- read_csv(file.path(data_dir, first_phase_filtered_data_file_name))
  bad_moderate_signal_df <<- read_csv(file.path(data_dir, bad_moderate_signal_file_name))
}

get_session_name <- function(session_abbr) {
  if (session_abbr=='RB') {
    return('RestingBaseline')
  } else if (session_abbr=='BW') {
    return('BaselineWriting')
  } else if (session_abbr=='ST') {
    return('BaselineWriting')
  } else if (session_abbr=='SC') {
    return('StressCondition')
  } else if (session_abbr=='DT') {
    return('DualTask')
  } else if (session_abbr=='P') {
    return('Presentation')
  }
  
}

replace_by_NA <- function(row_df) {
  print_msg(row_df['Subject'])
  print_msg(get_session_name(row_df['Session']))
  # print_msg(row_df['Signal'])
             
  second_phase_filtered_df[second_phase_filtered_df$Subject==row_df['Subject'] &
                           second_phase_filtered_df$Session==get_session_name(row_df['Session']),
                           row_df['Signal']] <<- NA
}

remove_full_bad_signal <- function() {
  bad_signal_df <- bad_moderate_signal_df %>% filter(Condition=='Bad')
  print_msg(bad_signal_df)
  
  invisible(apply(bad_signal_df, 1, function(row) replace_by_NA(row)))
  convert_to_csv(second_phase_filtered_df[order(second_phase_filtered_df$Subject),], 
                 file.path(data_dir, 'full_df_second_phase_filtered.csv'))
  
  mean_df <- second_phase_filtered_df %>% 
    select(-CovertedTime, -TimeElapsed, -Task) %>% 
    group_by(Subject,	Session, Condition) %>% 
    summarize_all(mean, na.rm=T) %>% 
    ungroup()
  
  convert_to_csv(mean_df, file.path(data_dir, 'result_df_second_phase.csv'))
}

remove_partial_bad_signal <- function(subj, session, signal, from, to) {
  second_phase_filtered_df[second_phase_filtered_df$Subject==subj &
                           second_phase_filtered_df$Session==get_session_name(session) &
                           second_phase_filtered_df$TimeElapsed >= from &
                           second_phase_filtered_df$TimeElapsed <= to,
                           signal] <<- NA
}

filter_data_second_phase <- function() {
  remove_partial_bad_signal('T092', 'RB', 'HR', from=0, to=34)
  remove_full_bad_signal()
}

``` 



```{r echo=FALSE, warning = FALSE, message = FALSE}
make_bad_moderate_signal_data()
read_data()
```

\newpage
```{r echo=FALSE, warning = FALSE, message = FALSE}
filter_data_second_phase()
```