---
title: "HR t-test - Bioharness & E4"
# output: pdf_document 
# fontsize: 44pt
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---


```{r echo = FALSE, warning = FALSE, message = FALSE} 

#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggpubr) 
library(directlabels)


#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
project_dir <- "T:/Google Drive/University of Houston/CS - UH/@Research - CPL/@Projects/NsfStressDataCuration/nsf-data-paper-scripts"
setwd(project_dir)

data_dir <- 'data'
plots_dir <- 'plots'

mean_file_name <- 'result_df.csv'
col_names <- c('Subject', 'Condition', 'Session', 'HR', 'N.HR')

# filtered_df <- tibble()
# raw_df <- tibble()

# plot_list <- list()



# session_atr <- 'all-session'
# session_list <- c('RestingBaseline', 'BaselineWriting', 'StressCondition', 'Presentation', 'DualTask')

# session_atr <- 'non-dual-session'
# session_list <- c('RestingBaseline', 'BaselineWriting', 'StressCondition', 'Presentation')

# session_atr <- 'dual-session'
# session_list <- c('DualTask')






#-------------------------#
#---FUNCTION DEFINITION---#
#-------------------------#
t_test_mean <- function() {
  mean_df <<- read_csv(file.path(data_dir, mean_file_name))[, col_names]
  mean_df <- mean_df %>% na.omit()
  
  t_test <- t.test(mean_df$HR, mean_df$N.HR, data=mean_df, paired=T, alternative='t')

  print(t_test)
  message(paste('p-value: ', t_test$p.value))
}

t_test_subtracting_baseline <- function() {
  mean_df <<- read_csv(file.path(data_dir, mean_file_name))[, col_names]
  # mean_df <- mean_df %>% na.omit()
  
  # subjects <- levels(factor(mean_df$Subject))
  # print(subjects)
  # for (subj in subjects) {
  #   subject_df <- mean_df %>% filter(Subject == subj)
  # }
  
  subj_df <- mean_df %>% 
    group_by(Subject) %>% 
    spread(Session, HR) %>%
    mutate(WB.RB = BaselineWriting - RestingBaseline, 
           SC.RB = StressCondition - RestingBaseline, 
           DT.RB = DualTask - RestingBaseline, 
           P.RB = Presentation - RestingBaseline)
  
  print(subj_df)
  
  # t_test <- t.test(mean_df$HR, mean_df$N.HR, data=mean_df, paired=T)

  # print(t_test)
  # message(paste('p-value: ', t_test$p.value))
}

``` 

\newpage
# Mean Heart Rate - Per Session
```{r echo=FALSE, warning = FALSE, message = FALSE}
t_test_mean()
```

<!-- \newpage   -->
<!-- # Heart Rate - Session-Baseline -->
<!-- ```{r echo=FALSE, warning = FALSE, message = FALSE}  -->
<!-- t_test_subtracting_baseline() -->
<!-- ```  -->