---
title: 'Psychometrics Data Analysis'
# output: pdf_document 
# fontsize: 44pt
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---


```{r echo = FALSE, warning = FALSE, message = FALSE} 

#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggpubr) 
library(directlabels)
library(gsubfn)

source('T:/Google Drive/University of Houston/CS - UH/@Research - CPL/@Projects/NsfStressDataCuration/@questionnaire_scoring.R')


#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
project_dir <- 'T:/Google Drive/University of Houston/CS - UH/@Research - CPL/@Projects/NsfStressDataCuration/nsf-data-paper-scripts'
setwd(project_dir)

data_dir <- 'data'
survey_data_dir <- 'survey-data'
plots_dir <- 'plots'

data_file_name <- 'result_df.csv'

pre_survey_file_name <- 'pre-survey.csv'
post_survey_file_name <- 'post-survey.csv'
good_subj_file_name <- 'subj_good_df.csv'

good_subj_list <- tibble()
pre_survey_df <- tibble()
post_survey_df <- tibble()

biographic_df <- tibble()
nasa_tlx_freq_df <- tibble()
erq_score_df <- tibble()
pss_score_df <- tibble()

na_val <- 'NA'


bio_ques_list <- c('City', 'State', 'Postal', 
                   'SubjectID', 'Age', 'Gender',
                   'Nationality', 'Other_Nationality', 'Native_Language', 'Other_Native_Language',
                   'Education', 'Occupation', 'Writing_Proficiency', 'Daily_Email_Frequency')

erq_ques_list <- c('SubjectID',
                   'ERQ_Q1', 'ERQ_Q2', 'ERQ_Q3', 'ERQ_Q4', 'ERQ_Q5',
                   'ERQ_Q6', 'ERQ_Q7', 'ERQ_Q8', 'ERQ_Q9', 'ERQ_Q10')

pss_ques_list <- c('SubjectID',
                   'PSS_Q1', 'PSS_Q2', 'PSS_Q3', 'PSS_Q4', 'PSS_Q5',
                   'PSS_Q6', 'PSS_Q7', 'PSS_Q8', 'PSS_Q9', 'PSS_Q10')

education_order <- c('High school or below', 'Undergraduate', 'Master or equivalent', 'PhD, JD, or equivalent')
occupation_order <- c('Undergraduate student', 'Graduate student', 'Staff')
writing_proficiency_order <- c('1=Not fluent at all', '2', '3', '4', '5', '6', '7=Very fluent')
email_freq_order <- c('1=Never', '2', '3', '4', '5', '6', '7=Very often')
nationality_order <- c('United States', 'Others')
native_lang_order <- c('English', 'Others')


nasa_tlx_ques_list <- c('Stress_Question', 'Nasa_Mental', 'Nasa_Physical', 'Nasa_Temporal',
                        'Nasa_Performance', 'Nasa_Effort', 'Nasa_Frustration') 
nasa_task_options <- c('Strongly disagree', 'Disagree', 'Somewhat disagree', 
                       'Neither agree or disagree', 'Somewhat agree', 'Agree', 'Strongly agree')



#-------------------------#
#---FUNCTION DEFINITION---#
#-------------------------#
convert_to_csv <- function(df, file_name) {
  write.table(df, file = file.path(data_dir, file_name), row.names=F, sep = ',')
}

remove_na <- function(df, col_list) {
  return(df[complete.cases(df[, col_list]), ])
}

get_significance_sign <- function(p_value) { 
  if (p_value > 0.05) { 
    return(' ') 
  } else if (p_value <= 0.001) { 
    return('***') 
  } else if (p_value <= 0.01) { 
    return('**') 
  } else if (p_value <= 0.05) { 
    return('*') 
  } 
} 

print_msg <- function(msg) {
  # cat(msg)
  print(msg)
  message(msg)
}

print_significance <- function(prop_test, alternative_val) {
  p_val <- prop_test$p.value
  if (p_val < 0.05) {
    print_msg(paste0(get_significance_sign(p_val), ' The proportion of agreement is significantly ', alternative_val))
  } else {
    print_msg(paste0('The proportion of agreement is NOT significantly ', alternative_val))
  }
  print_msg(paste0('than the proportion of disagreement, with a p-value = ', p_val))
}

is_match <- function(string_we_have, pattern_we_are_looking_for) { 
  return(grepl(pattern_we_are_looking_for, string_we_have)) 
} 

replace_dot_space <- function(str) {
  gsubfn('.', list('.' = '_', ' ' = '_'), tolower(str))
}

replace_underscore <- function(str) {
  gsubfn('.', list('_' = ' ', '-' = ' '), str)
}

save_plot <- function(plot_name, plot, default_width=15, default_height=10) {
  # print(plot)
  
  plot_path <- file.path(project_dir, plots_dir, paste0(plot_name, '.png'))
  ggsave(plot_path, plot, width=default_width, height=default_height)
  
  plot_path <- file.path(project_dir, plots_dir, paste0(plot_name, '.pdf'))
  ggsave(plot_path, plot, device=cairo_pdf, width=default_width, height=default_height)
}

read_data <- function() {
  pre_survey_df <<- read_csv(file.path(data_dir, survey_data_dir, pre_survey_file_name))
  post_survey_df <<- read_csv(file.path(data_dir, survey_data_dir, post_survey_file_name))
  good_subj_list <<- read_csv(file.path(data_dir, good_subj_file_name))
}

extract_nasa_tlx_score <- function() {
  nasa_tlx_df <<- post_survey_df[, c(22, seq(24, 30))]
  
  ## print_msg(colnames(nasa_tlx_df)) ## DO NOT DELETE
  colnames(nasa_tlx_df) <<- c('SubjectID', nasa_tlx_ques_list)
  ## print_msg(colnames(nasa_tlx_df)) ## DO NOT DELETE
  
  ## Filter out the data for good subject list only 
  nasa_tlx_df <<- nasa_tlx_df %>% 
    filter(SubjectID %in% good_subj_list$Subject)
  ## convert_to_csv(nasa_tlx_df, file.path(survey_data_dir, 'nasa_tlx_score.csv'))
}

draw_group_bar_chart_nasa_tlx <- function() {
  ## getting the answer frequency for each question
  nasa_tlx_freq_df <<- nasa_tlx_df %>%
    gather(Question, Answer, -SubjectID) %>% ## making the data wide to long for all signals
    select(-SubjectID) %>%                   ## We do not need the subject id
    group_by(Question, Answer) %>%
    summarize(Frequency=n())
  
  nasa_tlx_freq_df$Question <<- factor(nasa_tlx_freq_df$Question, levels=nasa_tlx_ques_list)  
  ## convert_to_csv(nasa_tlx_freq_df, file.path(survey_data_dir, 'nasa_tlx_for_plot.csv'))
  
  plot <- nasa_tlx_freq_df %>% 
    ggplot(aes(x=Answer, y=Frequency, fill=Question)) + 
    geom_bar(position='dodge', stat='identity') +
    scale_x_discrete(limits = nasa_task_options) +
    theme_bw() + 
    theme(text = element_text(size = 16),
          axis.title = element_text(size = 16, hjust = 0.5),
          axis.text.x = element_text(size = 8, angle = 45, hjust = 1),
          plot.title = element_text(hjust = 0.5, size = 20, face = 'bold')) 
  
  print(plot)
  
  plot <- plot + 
    theme(text = element_text(size = 20),
          axis.title = element_text(size = 20),
          axis.text.x = element_text(size = 16))
          # axis.text.x = element_text(size = 16, angle = 45, hjust = 1))
  
  save_plot('nasa_frequency', plot, 18)
}

get_nasa_bar_plot_df <- function(df) {
  df <- df %>%
    gather(Options, Frequency, -Question)
  return(df)
}

generate_nasa_bar_plot <- function(df, title) {
  plot <- get_nasa_bar_plot_df(df) %>%
    ggplot(aes(x=Options, y=Frequency)) +
    geom_bar(stat='identity') +
    ggtitle(replace_underscore(title)) +
    scale_x_discrete(labels=c('agree_freq' = 'Agreement', 'disagree_freq' = 'Disagreement')) +
    theme_bw() + 
    theme(text = element_text(size = 16),
          axis.title = element_text(size = 16, hjust = 0.5),
          axis.text.x = element_text(size = 12),
          plot.title = element_text(size = 20, hjust = 0.5, face = 'bold')) 
  
  
  print_plot <- plot + geom_text(aes(label=paste0('n = ', Frequency)), vjust=-0.2)
  print(print_plot)
  
  plot <- plot + 
    geom_text(aes(label=paste0('n = ', Frequency)), vjust=-0.2, size=8) +
    theme(text = element_text(size = 20),
          axis.title = element_text(size = 20),
          axis.text.x = element_text(size = 16))

  save_plot(tolower(title), plot)
}

generate_prop_test <- function(df, nasa_ques, comparison_option, alternative_val) {
  total_response <- nrow(nasa_tlx_df)
  
  agree_df <- df %>%
    filter(Answer > comparison_option) %>% 
    summarize(agree_freq = sum(Frequency))
    
  disagree_df <- df %>% 
    filter(Answer <= comparison_option) %>% 
    summarize(disagree_freq = sum(Frequency))
  
  freq_df <- merge(agree_df, disagree_df, by='Question')
  # print_msg(str(freq_df))
  
  generate_nasa_bar_plot(freq_df, nasa_ques)
    
  print_msg(paste0(nasa_ques, ':'))
  print_msg(paste0('Agree: ', freq_df$agree_freq))
  print_msg(paste0('Disagree: ', freq_df$disagree_freq))
  
  prop_test <- prop.test(c(freq_df$agree_freq, freq_df$disagree_freq),
            c(total_response, total_response),
            p = NULL,
            alternative = alternative_val,
            correct = T)
  print_msg(prop_test)
  print_significance(prop_test, alternative_val)
}


get_proportion_test_nasa_tlx <- function() {
  for (nasa_ques in nasa_tlx_ques_list) {
    temp_nasa_tlx_freq_df <- nasa_tlx_freq_df[nasa_tlx_freq_df$Question==nasa_ques, ]
    
    generate_prop_test(temp_nasa_tlx_freq_df, nasa_ques, 4, 'greater')
    if (nasa_ques=='Nasa_Performance') {
      generate_prop_test(temp_nasa_tlx_freq_df, nasa_ques, 3, 'less')
    }
  }
}

extract_biographic_info <- function() {
  biographic_df <<- pre_survey_df[, c(19:32)]
  
  # print_msg(colnames(biographic_df)) ## DO NOT DELETE
  colnames(biographic_df) <<- bio_ques_list
  # print_msg(colnames(biographic_df)) ## DO NOT DELETE
  
  
  ## Filter out the data for good subject list only 
  biographic_df <<- biographic_df %>% 
    filter(SubjectID %in% good_subj_list$Subject)
  print_msg(str(biographic_df))
}

get_bio_bar_plot_df <- function(col_name) {
  df <- remove_na(biographic_df, col_name) 
  if (col_name == 'Gender') {
    df <- df %>% mutate(Gender = recode(Gender, '1' = 'Male', '2' = 'Female'))
  } else if (col_name == 'Education') {
    df <- df %>% mutate(Education = recode(Education, 
                                        '1' = 'High school or below', 
                                        '2' = 'Undergraduate',
                                        '3' = 'Master or equivalent',
                                        '4' = 'PhD, JD, or equivalent'))
  } else if (col_name == 'Occupation') {
    df <- df %>% mutate(Occupation = recode(Occupation, 
                                        '1' = 'Undergraduate student', 
                                        '2' = 'Graduate student',
                                        '3' = 'Staff'))
  } else if (col_name == 'Writing_Proficiency') {
    df <- df %>% mutate(Writing_Proficiency = recode(Writing_Proficiency, 
                                        '1' = '1=Not fluent at all', 
                                        '2' = '2',
                                        '3' = '3',
                                        '4' = '4', 
                                        '5' = '5',
                                        '6' = '6',
                                        '7' = '7=Very fluent'))
  } else if (col_name == 'Daily_Email_Frequency') {
    df <- df %>% mutate(Daily_Email_Frequency = recode(Daily_Email_Frequency, 
                                        '1' = '1=Never', 
                                        '2' = '2',
                                        '3' = '3',
                                        '4' = '4', 
                                        '5' = '5',
                                        '6' = '6',
                                        '7' = '7=Very often'))
  } else if (col_name == 'Nationality') {
    df <- df %>% mutate(Nationality = recode(Nationality, 
                                        '1' = 'United States', 
                                        '2' = 'Others'))
  } else if (col_name == 'Native_Language') {
    df <- df %>% mutate(Native_Language = recode(Native_Language, 
                                        '1' = 'English', 
                                        '2' = 'Others'))
  }
  
  return(df)
}


get_angle <- function(col_name) {
  if (col_name %in% c('Education', 'Occupation')) {
    return(25)
  }
  
  return(0)
}

get_hjust <- function(col_name) {
  if (col_name %in% c('Education', 'Occupation')) {
    return(1)
  }
  
  return(0.5)
}

get_order <- function(col_name) {
  if (col_name == 'Education') {
    return(education_order)
  } else if (col_name == 'Occupation') {
    return(occupation_order)
  } else if (col_name == 'Writing_Proficiency') {
    return(writing_proficiency_order)
  } else if (col_name == 'Daily_Email_Frequency') {
    return(email_freq_order)
  } else if (col_name == 'Nationality') {
    return(nationality_order)
  } else if (col_name == 'Native_Language') {
    return(native_lang_order)
  }
}

get_x_lab <- function(col_name) {
  if (col_name == 'Education') {
    return(paste0(col_name, ' Levels'))
  }
  
  return(col_name)
}

get_ggplot <- function(df, col_name) {
  if (col_name == 'Gender') {
    return(ggplot(data=df, aes(x=df[[col_name]], fill=df[[col_name]])))
  }
  
  return(ggplot(data=df, aes(x=df[[col_name]])))
}
  

draw_distribution <- function(col_name) {
  plot_df <- get_bio_bar_plot_df(col_name)
  
  title <- paste0(replace_underscore(col_name), ' Distribution')
  y_lab <- 'Count'
  
  plot <- get_ggplot(plot_df, col_name) +
    geom_bar() +
    ggtitle(title) +
    xlab(get_x_lab(replace_underscore(col_name))) + 
    ylab(y_lab) +
    scale_x_discrete(limits = get_order(col_name)) +
    theme_bw() +
    theme(legend.position = 'none',
          plot.title = element_text(hjust = 0.5),
          text = element_text(size = 20),
          axis.title = element_text(size = 20),
          axis.text.x = element_text(size = 16, angle = get_angle(col_name), hjust = get_hjust(col_name)))

  print(plot)
  save_plot(replace_dot_space(title), plot)
}


get_biographic_distribution <- function() {
  draw_distribution('Age')
  draw_distribution('Gender')
  draw_distribution('Education')
  draw_distribution('Occupation')
  draw_distribution('Writing_Proficiency')
  draw_distribution('Daily_Email_Frequency')
  draw_distribution('Nationality')
  draw_distribution('Native_Language')
}

extract_erq_score_each_row <- function(current_subj_df) {
  temp_erq_cog_df <- tibble('Subject' = current_subj_df['SubjectID'],
                          'Title' = 'ERQ: Cognitive Reappraisal',
                          'Value' = get_erq_cog_score(current_subj_df),
                          'MinVal' = 6,
                          'MaxVal' = 42)
  
  temp_erq_sup_df <- tibble('Subject' = current_subj_df['SubjectID'],
                          'Title' = 'ERQ: Expressive Suppression',
                          'Value' = get_erq_sup_score(current_subj_df),
                          'MinVal' = 4,
                          'MaxVal' = 28)
  
  temp_erq_score_df <- rbind(temp_erq_cog_df, temp_erq_sup_df)
  
  if (nrow(erq_score_df) == 0) {
    erq_score_df <<- temp_erq_score_df
  } else {
    erq_score_df <<- rbind(erq_score_df, temp_erq_score_df)
  }
}

extract_erq_score <- function() {
  erq_df <- post_survey_df[, c(22, seq(30, 39))]
  
  # message(colnames(erq_df)) ## DO NOT DELETE
  colnames(erq_df) <- erq_ques_list
  # print_msg(colnames(erq_df)) ## DO NOT DELETE
  
  ## Filter out the data for good subject list only 
  erq_df <- erq_df %>% 
    filter(SubjectID %in% good_subj_list$Subject)
  print_msg(str(erq_df))
  
  apply(erq_df, 1, function(each_row) extract_erq_score_each_row(each_row))
  
  convert_to_csv(erq_score_df[order(erq_score_df$Subject),], file.path(survey_data_dir, 'erq_score.csv'))
}


extract_pss_score_each_row <- function(current_subj_df) {
  temp_pss_score_df <- tibble("Subject" = current_subj_df['SubjectID'],
                          "Title" = "Percieved Stress Scale",
                          "Value" = get_pss_score(current_subj_df),
                          "MinVal" = 0,
                          "MaxVal" = 40)
  
  # temp_pss_score_df <- rbind(temp_pss_cog_df, temp_pss_sup_df)
  
  if (nrow(pss_score_df) == 0) {
    pss_score_df <<- temp_pss_score_df
  } else {
    pss_score_df <<- rbind(pss_score_df, temp_pss_score_df)
  }
}

extract_pss_score <- function() {
  pss_df <- pre_survey_df[, c(22, seq(33, 42))]
  
  message(colnames(pss_df)) ## DO NOT DELETE
  colnames(pss_df) <- pss_ques_list
  print_msg(colnames(pss_df)) ## DO NOT DELETE
  
  ## Filter out the data for good subject list only 
  pss_df <- pss_df %>% 
    filter(SubjectID %in% good_subj_list$Subject)
  print_msg(str(pss_df))
  
  apply(pss_df, 1, function(each_row) extract_pss_score_each_row(each_row))
  convert_to_csv(pss_score_df[order(pss_score_df$Subject),], file.path(survey_data_dir, 'pss_score.csv'))
}
``` 


<!-- READ DATA GLOBLALLY -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
read_data()
```


<!-- BIOGRAPHIC DISTRIBUTION -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
# extract_biographic_info()
# get_biographic_distribution()
```


<!-- NASA TASK PLOTS -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
# extract_nasa_tlx_score()
# draw_group_bar_chart_nasa_tlx()
```

<!-- NASA TASK PROPORTION TEST -->
\newpage
```{r echo=FALSE, warning = FALSE, message = FALSE}
# get_proportion_test_nasa_tlx()
```


<!-- Perceived Stress Scale Plots -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
extract_pss_score()
```


<!-- Emotion Regulation Plots -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
extract_erq_score()
```
