---
title: "Supplimentary Plots"
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
output:
  pdf_document: default
  html_document: default
geometry: top=3.5cm, bottom=3cm
---


```{r echo = FALSE, warning = FALSE, message = FALSE} 

#-------------------------#
#--------LIBRARIES--------#
#-------------------------#
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(gridExtra)
library(ggpubr)
# library(directlabels)
library(gsubfn)

# source('T:/Google Drive/University of Houston/CS - UH/@Research - CPL/@Projects/NsfStressDataCuration/nsf-data-paper-scripts/@multiplot.R')


#-------------------------#
#-----GLOBAL VARIABLES----#
#-------------------------#
root_dir <- 'T:/Google Drive/University of Houston/CS - UH/@Research - CPL/@Projects/NsfStressDataCuration'
setwd(root_dir)

# raw_data_dir <- 'nsf-stress-study'
# super_session_pattern <- '^SuperSession$' 
# performance_data_dir <- file.path(data_dir, 'performane-data')

data_paper_dir <- file.path(root_dir, 'nsf-data-paper-scripts')
data_dir <- file.path(data_paper_dir, 'data')
plots_dir <- file.path(data_paper_dir, 'plots')

session_list <- c('RestingBaseline', 'BaselineWriting', 'DualTask', 'Presentation', 'StressCondition')

# filtered_data_file_name <- 'full_df_non_filtered.csv'
# mean_data_file_name <- 'need_to_change.csv' ##NEED TO CHANGE!!!!
# hr_col_names <- c('HR.non.filtered', 'N.HR.non.filtered')
# eda_col_name <- 'N.EDA.non.filtered'

filtered_data_file_name <- 'full_df_filtered.csv'
mean_data_file_name <- 'result_df.csv'
hr_col_names <- c('HR', 'N.HR')
eda_col_name <- 'N.EDA'



# good_subj_file_name <- 'subj_good_df.csv'

filtered_df <- tibble()
mean_df <- tibble()
mean_of_mean_df <- tibble()
``` 


```{r echo=FALSE, warning = FALSE, message = FALSE}
convert_to_csv <- function(df, file_name) {
  write.table(df, file = file.path(file_name), row.names=F, sep = ',')
}

print_msg <- function(msg) {
  print(msg)
  message(msg)
}

is_match <- function(str, pattern) { 
  return(grepl(pattern, str)) 
}

figure_out_labels <- function(col_name) { 
  if (is_match(col_name, 'HR')) { 
    return('Heart Rate [BPM]') 
  } else if (is_match(col_name, 'N.EDA')) { 
    return(expression(paste('EDA [', mu, 'S]'))) 
  } 
  return('Unknown axis')
}

#---- Add one space if it finds any CamelCase ----#
get_session_name <- function(session_name) {
  if (session_name == 'BaselineWriting') {
    return('Single Task')
  }
  return(gsub("([a-z])([A-Z])", "\\1 \\2", session_name))
}

read_data <- function() {
  filtered_df <<- read_csv(file.path(data_dir, filtered_data_file_name))
  mean_df <<- read_csv(file.path(data_dir, mean_data_file_name))
  mean_of_mean_df <<- mean_df %>% 
    select(-Subject, -Condition) %>% 
    group_by(Session) %>% 
    summarise_each(funs(mean(., na.rm = TRUE)))
  # print_msg(mean_of_mean_df)
  # print_msg(mean_of_mean_df[mean_of_mean_df$Session=='RestingBaseline', 'PP'])
  
  # convert_to_csv(mean_of_mean_df, file.path(data_dir, 'mean_of_mean.csv'))
}


get_mean <- function(session, col_name) {
  mean <- mean_of_mean_df %>%
    filter(Session==session) %>%
    select(col_name) %>% 
    unlist(.)
  return(mean)
}

draw_plots <- function() {
  # subj_list <- levels(factor(filtered_df$Subject))
  # subj_list <- c('T031', 'T032', 'T132')
  # subj_list <- c('T031', 'T032')
  subj_list <- c('T031')
  
  for(subj in subj_list) {
    
    # hr_plot_list <- list()
    # eda_plot_list <- list()
    plot_list <- list()
    
    for (session in session_list) {
      df <- filtered_df %>% 
        filter(Subject==subj, Session==session)
      # print_msg(str(df))
      
      
      ##########################################################################################################
      ##------------------------------------ MAKE DATA LONG AND PLOT -----------------------------------------##
      ##----https://markhneedham.com/blog/2014/09/16/r-ggplot-plotting-multiple-variables-on-a-line-chart/----##
      ##########################################################################################################
      hr_plot <- df %>%
        ggplot(aes(x=TimeElapsed)) +
        geom_line(aes(y=df[[hr_col_names[1]]]), color='coral') +
        geom_line(aes(y=df[[hr_col_names[2]]]), color='dodgerblue') +
        ggtitle(paste0(subj, ': ', get_session_name(session))) +
        xlab('Time [s]') +
        ylab(figure_out_labels('HR')) +
        geom_hline(yintercept=c(get_mean(session, hr_col_names[1]), get_mean(session, hr_col_names[2])), 
                   linetype="dashed", 
                   size=1.2,
                   color=c('coral3', 'dodgerblue3')) +
        theme(plot.title = element_text(hjust = 0.5, face = "bold"))
      
      # print(hr_plot)
      
      
      eda_plot <- df %>%
        ggplot(aes(TimeElapsed, df[[eda_col_name]])) +
        geom_line(color='mediumseagreen') +
        ggtitle(paste0(subj, ': ', get_session_name(session))) +
        xlab('Time [s]') +
        ylab(figure_out_labels(eda_col_name)) +
        geom_hline(yintercept=get_mean(session, eda_col_name), 
                   linetype="dashed", 
                   size=1.2,
                   color="darkgreen") +
        theme(plot.title = element_text(hjust = 0.5, face = "bold"))

      # print(eda_plot)
      grid_plot <- grid.arrange(hr_plot, eda_plot, ncol=2)
      
      # plot_list[[length(plot_list)+1]] <- hr_plot
      # plot_list[[length(plot_list)+1]] <- eda_plot
      
      # hr_plot_list[[length(hr_plot_list)+1]] <- hr_plot
      # eda_plot_list[[length(eda_plot_list)+1]] <- eda_plot
    }
    
    # print_msg(length(plot_list))
    # grid.arrange(plot_list, ncol=2)
    # do.call('grid.arrange', c(plot_list, ncol=2))
    # grid_plot <- grid.arrange(plot_list)
    # multiplot(plot_list, cols=2)
    # ggarrange(plot_list)
    cat("\n\n\n\\newpage\n")
  }
}
```

<!-- READ DATA GLOBLALLY -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
read_data()
```

\newpage
<!-- DRAW PLOTS -->
```{r echo=FALSE, warning = FALSE, message = FALSE}
draw_plots()
```
